resources:
  - name: resource_1
    type: PropertyBag
    configuration:
      test: one
  - name: resource_2
    type: PropertyBag
    configuration:
      test: two
  - name: resource_3
    type: PropertyBag
    configuration:
      test: three
  - name: resource_4
    type: PropertyBag
    configuration:
      test: four
  - name: resource_5
    type: PropertyBag
    configuration:
      test: five
  - name: resource_6
    type: PropertyBag
    configuration:
      test: six
  - name: resource_7
    type: PropertyBag
    configuration:
      test: seven
  - name: resource_8
    type: PropertyBag
    configuration:
      test: eight
  - name: resource_9
    type: PropertyBag
    configuration:
      test: nine
  - name: resource_10
    type: PropertyBag
    configuration:
      test: ten
  - name: resource_11
    type: PropertyBag
    configuration:
      test: eleven
  - name: resource_12
    type: PropertyBag
    configuration:
      test: twelve
  - name: resource_13
    type: PropertyBag
    configuration:
      test: thirteen
  - name: resource_14
    type: PropertyBag
    configuration:
      test: fourteen
  - name: resource_15
    type: PropertyBag
    configuration:
      test: fifteen
  - name: resource_16
    type: PropertyBag
    configuration:
      test: sixteen
  - name: resource_17
    type: PropertyBag
    configuration:
      test: seventeen
  - name: resource_18
    type: PropertyBag
    configuration:
      test: eighteen
  - name: resource_19
    type: PropertyBag
    configuration:
      test: nineteen
  - name: repo_resource
    type: GitRepo
    configuration:
      path: a-murphy/5testRename5
      gitProvider: aidan_github
pipelines:
  - name: test_pipeline
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: repo_resource
        execution:
          onExecute:
            - echo "test"
      - name: step_2
        type: Bash
        configuration:
          inputResources:
            - name: repo_resource
          integrations:
            - name: aidan_github
        execution:
          onExecute:
            - echo "test"
      - name: step_3
        type: Bash
        configuration:
          inputSteps:
            - name: step_1
          outputResources:
            - name: resource_1
        execution:
          onExecute:
            - write_output resource_1 test="$step_name"
            
      - name: step_4
        type: Bash
        configuration:
          inputResources:
            - name: resource_1
          outputResources:
            - name: resource_2
        execution:
          onExecute:
            - write_output resource_2 test="$step_name"
            
      - name: step_5
        type: Bash
        configuration:
          priority: 10
          inputResources:
            - name: resource_2
          outputResources:
            - name: resource_3
        execution:
          onExecute:
            - write_output resource_3 test="$step_name"
            
      - name: step_6
        type: Bash
        configuration:
          priority: 5
          inputResources:
            - name: resource_3
          outputResources:
            - name: resource_4
        execution:
          onExecute:
            - write_output resource_4 test="$step_name"
      - name: step_7
        type: Bash
        configuration:
          inputResources:
            - name: resource_4
          outputResources:
            - name: resource_5
        execution:
          onExecute:
            - write_output resource_5 test="$step_name"
      - name: step_8
        type: Bash
        configuration:
          inputResources:
            - name: resource_5
          outputResources:
            - name: resource_6
        execution:
          onExecute:
            - write_output resource_6 test="$step_name"
      - name: step_9
        type: Bash
        configuration:
          priority: 10
          inputResources:
            - name: resource_6
          outputResources:
            - name: resource_7
        execution:
          onExecute:
            - write_output resource_7 test="$step_name"
      - name: step_10
        type: Bash
        configuration:
          priority: 5
          inputResources:
            - name: resource_7
          outputResources:
            - name: resource_8
        execution:
          onExecute:
            - write_output resource_8 test="$step_name"
      - name: step_11
        type: Bash
        configuration:
          inputResources:
            - name: repo_resource
            - name: resource_8
          outputResources:
            - name: resource_9
        execution:
          onExecute:
            - write_output resource_9 test="$step_name"
      - name: step_12
        type: Bash
        configuration:
          inputResources:
            - name: repo_resource
            - name: resource_9
          integrations:
            - name: aidan_github
          outputResources:
            - name: resource_10
        execution:
          onExecute:
            - write_output resource_10 test="$step_name"
      - name: step_13
        type: Bash
        configuration:
          inputSteps:
            - name: step_1
          outputResources:
            - name: resource_11
        execution:
          onExecute:
            - write_output resource_1 test="$step_name"
      - name: step_14
        type: Bash
        configuration:
          inputResources:
            - name: resource_11
          outputResources:
            - name: resource_12
        execution:
          onExecute:
            - write_output resource_12 test="$step_name"
      - name: step_15
        type: Bash
        configuration:
          priority: 10
          inputResources:
            - name: resource_12
          outputResources:
            - name: resource_13
        execution:
          onExecute:
            - write_output resource_13 test="$step_name"
      - name: step_16
        type: Bash
        configuration:
          priority: 5
          inputResources:
            - name: resource_13
          outputResources:
            - name: resource_14
        execution:
          onExecute:
            - write_output resource_14 test="$step_name"
      - name: step_17
        type: Bash
        configuration:
          inputResources:
            - name: resource_14
          outputResources:
            - name: resource_15
        execution:
          onExecute:
            - write_output resource_15 test="$step_name"
      - name: step_18
        type: Bash
        configuration:
          inputResources:
            - name: resource_15
          outputResources:
            - name: resource_16
        execution:
          onExecute:
            - write_output resource_16 test="$step_name"
      - name: step_19
        type: Bash
        configuration:
          priority: 10
          inputResources:
            - name: resource_16
          outputResources:
            - name: resource_17
        execution:
          onExecute:
            - write_output resource_17 test="$step_name"
      - name: step_20
        type: Bash
        configuration:
          priority: 5
          inputResources:
            - name: resource_17
          outputResources:
            - name: resource_18
        execution:
          onExecute:
            - write_output resource_18 test="$step_name"
      - name: step_21
        type: Bash
        configuration:
          inputResources:
            - name: repo_resource
            - name: resource_18
          integrations:
            - name: aidan_github
          outputResources:
            - name: resource_19
        execution:
          onExecute:
            - write_output resource_19 test="$step_name"
      - name: step_22
        type: Bash
        configuration:
          inputResources:
            - name: repo_resource
            - name: resource_19
          integrations:
            - name: aidan_github
          outputResources:
            - name: resource_20
        execution:
          onExecute:
            - write_output resource_20 test="$step_name"
      - name: step_23
        type: Bash
        configuration:
          inputSteps:
            - name: step_1
          outputResources:
            - name: resource_1
        execution:
          onExecute:
            - write_output resource_1 test="$step_name"
      - name: step_24
        type: Bash
        configuration:
          inputResources:
            - name: resource_1
          outputResources:
            - name: resource_2
        execution:
          onExecute:
            - write_output resource_2 test="$step_name"
      - name: step_25
        type: Bash
        configuration:
          priority: 10
          inputResources:
            - name: resource_2
          outputResources:
            - name: resource_3
        execution:
          onExecute:
            - write_output resource_3 test="$step_name"
      - name: step_26
        type: Bash
        configuration:
          priority: 5
          inputResources:
            - name: resource_3
          outputResources:
            - name: resource_4
        execution:
          onExecute:
            - write_output resource_4 test="$step_name"
      - name: step_27
        type: Bash
        configuration:
          inputResources:
            - name: resource_4
          outputResources:
            - name: resource_5
        execution:
          onExecute:
            - write_output resource_5 test="$step_name"
      - name: step_28
        type: Bash
        configuration:
          inputResources:
            - name: resource_5
          outputResources:
            - name: resource_6
        execution:
          onExecute:
            - write_output resource_6 test="$step_name"
            
      - name: step_29
        type: Bash
        configuration:
          priority: 10
          inputResources:
            - name: resource_6
          outputResources:
            - name: resource_7
        execution:
          onExecute:
            - write_output resource_7 test="$step_name"
            
      - name: step_30
        type: Bash
        configuration:
          priority: 5
          inputResources:
            - name: resource_7
          outputResources:
            - name: resource_8
        execution:
          onExecute:
            - write_output resource_8 test="$step_name"
            
      - name: step_31
        type: Bash
        configuration:
          inputResources:
            - name: repo_resource
            - name: resource_8
          integrations:
            - name: aidan_github
          outputResources:
            - name: resource_9
        execution:
          onExecute:
            - write_output resource_9 test="$step_name"
            - echo "test"
      - name: step_32
        type: Bash
        configuration:
          inputResources:
            - name: repo_resource
          integrations:
            - name: aidan_github
          outputResources:
            - name: resource_10
        execution:
          onExecute:
            - write_output resource_10 test="$step_name"
            - echo "test"
      - name: step_33
        type: Bash
        configuration:
          inputSteps:
            - name: step_1
          outputResources:
            - name: resource_11
        execution:
          onExecute:
            - write_output resource_11 test="$step_name"
            
      - name: step_34
        type: Bash
        configuration:
          inputResources:
            - name: resource_11
          outputResources:
            - name: resource_12
        execution:
          onExecute:
            - write_output resource_12 test="$step_name"
            
      - name: step_35
        type: Bash
        configuration:
          priority: 10
          inputResources:
            - name: resource_12
          outputResources:
            - name: resource_13
        execution:
          onExecute:
            - write_output resource_13 test="$step_name"
            
      - name: step_36
        type: Bash
        configuration:
          priority: 5
          inputResources:
            - name: resource_13
          outputResources:
            - name: resource_14
        execution:
          onExecute:
            - write_output resource_14 test="$step_name"
            
      - name: step_37
        type: Bash
        configuration:
          inputResources:
            - name: resource_14
          outputResources:
            - name: resource_15
        execution:
          onExecute:
            - write_output resource_15 test="$step_name"
            
      - name: step_38
        type: Bash
        configuration:
          inputResources:
            - name: resource_15
          outputResources:
            - name: resource_16
        execution:
          onExecute:
            - write_output resource_16 test="$step_name"
            
      - name: step_39
        type: Bash
        configuration:
          priority: 10
          inputResources:
            - name: resource_16
          outputResources:
            - name: resource_17
        execution:
          onExecute:
            - write_output resource_17 test="$step_name"
            
      - name: step_40
        type: Bash
        configuration:
          priority: 5
          inputResources:
            - name: resource_17
          outputResources:
            - name: resource_18
        execution:
          onExecute:
            - write_output resource_18 test="$step_name"
            
      - name: step_41
        type: Bash
        configuration:
          inputResources:
            - name: repo_resource
            - name: resource_18
          integrations:
            - name: aidan_github
          outputResources:
            - name: resource_19
        execution:
          onExecute:
            - write_output resource_19 test="$step_name"
            - echo "test"
      - name: step_42
        type: Bash
        configuration:
          inputResources:
            - name: repo_resource
          integrations:
            - name: aidan_github
          outputResources:
            - name: resource_20
        execution:
          onExecute:
            - write_output resource_20 test="$step_name"
            - echo "test"
      - name: step_43
        type: Bash
        configuration:
          inputSteps:
            - name: step_1
          outputResources:
            - name: resource_1
        execution:
          onExecute:
            - write_output resource_1 test="$step_name"
            
      - name: step_44
        type: Bash
        configuration:
          inputResources:
            - name: resource_1
          outputResources:
            - name: resource_2
        execution:
          onExecute:
            - write_output resource_2 test="$step_name"
            
      - name: step_45
        type: Bash
        configuration:
          priority: 10
          inputResources:
            - name: resource_2
          outputResources:
            - name: resource_3
        execution:
          onExecute:
            - write_output resource_3 test="$step_name"
            
      - name: step_46
        type: Bash
        configuration:
          priority: 5
          inputResources:
            - name: resource_3
          outputResources:
            - name: resource_4
        execution:
          onExecute:
            - write_output resource_4 test="$step_name"
            
      - name: step_47
        type: Bash
        configuration:
          inputResources:
            - name: resource_4
          outputResources:
            - name: resource_5
        execution:
          onExecute:
            - write_output resource_5 test="$step_name"
            
      - name: step_48
        type: Bash
        configuration:
          inputResources:
            - name: resource_5
          outputResources:
            - name: resource_6
        execution:
          onExecute:
            - write_output resource_6 test="$step_name"
            
      - name: step_49
        type: Bash
        configuration:
          priority: 10
          inputResources:
            - name: resource_6
          outputResources:
            - name: resource_7
        execution:
          onExecute:
            - write_output resource_7 test="$step_name"
            
      - name: step_50
        type: Bash
        configuration:
        priority: 5
        inputResources:
          - name: resource_7
        outputResources:
          - name: resource_8
        execution:
          onExecute:
            - write_output resource_8 test="$step_name"
        
