resources:
  - name: bitbucketRepoResource
    type: GitRepo
    repoPath: a-murphy/sample_pipelines3_rename
    configuration:
      gitProvider: bitbucket
      buildOn:
         pullRequestClose: true
         release: true
         tagPush: true

  - name: gitRepoResource
    type: GitRepo
    repoPath: a-murphy/5testRename5
    configuration:
      gitProvider: github
      buildOn:
         pullRequestClose: false
         release: true
         tagPush: true

  - name: gitRepoResource2
    type: GitRepo
    repoPath: a-murphy/5testRename5
    configuration:
      gitProvider: github
      buildOn:
         commit: false
         pullRequest: false
         pullRequestClose: false
         release: false
         tagPush: false
      tags:
        only: tag1|tag2
      branches:
        only: master|test
      
  - name: nodeRepoResource
    type: GitRepo
    repoPath: a-murphy/basic-node
    configuration:
      gitProvider: github
      buildOn:
         commit: true
         pullRequest: true
         pullRequestClose: false
         release: true
         tagPush: true
       
pipelines:
  - name: test_pipeline_10
    configuration:
      runtime:            
        type: host
    steps:
      - name: in_trigger_step
        type: bash
        configuration:
          runtime:            
            type: host
            image:
              language: java
              versions: v1.1
            custom: 
              name: drydock/u16javall
              tag:  v7.1.4
        execution:
          onExecute:
            - bump_semver v1.2.3 minor
            - echo "executing task command 1"
            - echo "executing task command 2"
            - openssl genrsa -out key.pem 1024 
            - openssl rsa -in key.pem -text -noout 
            - openssl rsa -in key.pem -pubout -out pub.pem 
            - openssl rsa -in pub.pem -pubin -text -noout 
            - echo "testing encryption" > testfile.txt
            - encrypt_file --output testencrypted.txt testfile.txt --key pub.pem
            - cat testencrypted.txt
            - decrypt_file testencrypted.txt --output testunencrypted.txt --key key.pem
            - cat testunencrypted.txt
            - encrypt_string "encryptme" --key pub.pem
            - encryptedstring=$(encrypt_string "encryptme" --key pub.pem)
            - echo "$encryptedstring"
            - decrypt_string "$encryptedstring" --key key.pem

      - name: main_step
        type: bash
        configuration:
          runtime:            
            type: image
            image:
              custom: 
                name: drydock/u16nodall
                tag:  v7.1.4
        requires:
          resources:
            - nodeRepoResource
        triggeredBy:
          steps:
            - in_trigger_step
        execution:
          onStart:
            - echo "Prepping build environment"
          onExecute:
            - echo "executing task command 1"
            - echo "executing task command 2"
            - compare_git --resource nodeRepoResource
            - cd "$res_nodeRepoResource_resourcePath"
            - switch_env nodejs 0.12
            - npm install
            - cd tests
            - ../node_modules/.bin/mocha --recursive "**/*.spec.js" -R mocha-junit-reporter --reporter-options mochaFile=../testresults.xml
            - ../node_modules/.bin/istanbul --include-all-sources cover -root "../routes" ../node_modules/mocha/bin/_mocha -- -R spec-xunit-file --recursive "**/*.spec.js"
            - ../node_modules/.bin/istanbul report cobertura --dir ../coverageReport
            - cd .. && ls
            - save_tests testresults.xml
            
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete: #always
            - echo "Cleaning up some stuff"
          onCancel:
            - echo "Someone cancelled the job"
      - name: other_step
        type: bash
        configuration:
          runtime:            
            type: host
        requires:
          integrations:
            - github
        triggeredBy:
          steps:
            - main_step
        execution:
          onStart:
            - echo "Prepping build environment"
          onExecute:
            - echo "executing task command 1"
            - echo "executing task command 2"
            - restore_run_state myYml testyml.yml
            - restore_run_state myWildcard testing/test
            - ls -R
            - ls -R $RUN_DIR
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete: #always
            - echo "Cleaning up some stuff"
          onCancel:
            - echo "Someone cancelled the job"
