pipelines:
  - name: test_pipeline_1
    runtime:            
      type: host
    steps:  
      - name: step_1
        type: Bash
        execution:
          onStart:
            - echo "Prepping build environment"
          onExecute:
            - echo "executing task command"
      - name: step_2
        type: Bash
        configuration:
          inputSteps:
            - name: step_1
        execution:
          onStart:
            - echo "Prepping build environment"
          onExecute:
            - echo "executing task command"
      - name: step_3
        type: Bash
        configuration:
          inputSteps:
            - name: step_2
        execution:
          onStart:
            - echo "Prepping build environment"
          onExecute:
            - echo "executing task command"
      - name: step_4
        type: Bash
        configuration:
          inputSteps:
            - name: step_3
        execution:
          onStart:
            - echo "Prepping build environment"
          onExecute:
            - echo "executing task command"
      - name: step_5
        type: Bash
        configuration:
          inputSteps:
            - name: step_4
        execution:
          onStart:
            - echo "Prepping build environment"
          onExecute:
            - echo "executing task command"
      - name: step_6
        type: Bash
        configuration:
          inputSteps:
            - name: step_5
        execution:
          onStart:
            - echo "Prepping build environment"
          onExecute:
            - echo "executing task command"
      - name: step_7
        type: Bash
        configuration:
          inputSteps:
            - name: step_6
        execution:
          onStart:
            - echo "Prepping build environment"
          onExecute:
            - echo "executing task command"
      - name: step_8
        type: Bash
        configuration:
          inputSteps:
            - name: step_7
        execution:
          onStart:
            - echo "Prepping build environment"
          onExecute:
            - echo "executing task command"
