resources:
 # - name: gitRepoResource
 #   type: GitRepo
 #   configuration:
 #     gitProvider: aidan_github
 #     path: a-murphy/5testRename5
 #     buildOn:
 #        pullRequestClose: false
 #        releaseCreate: true
 #        tagCreate: true
  - name: file
    type: remoteFile
    configuration:
      source: ftpIntegration2
      fileLocation: /home/test
      fileName: test.txt
  - name: awsFile
    type: Remotefile
    configuration:
      source: AWS
      fileLocation: ${versionTag}
      fileName: test.txt
  - name: artifactoryFile
    type: RemoteFile
    configuration:
      source: artifactory
      fileLocation: ${versionTag}
      fileName: test.txt
  - name: gcloudFile
    type: RemoteFile
    configuration:
      source: gcloud
      fileLocation: ${versionTag}
      fileName: test.txt
      
  - name: cluster
    type: vmCluster
    configuration:
      sshKey: sshKey
      targets:
        - targetOne

#  - name: gitRepoResource2
#    type: GitRepo
#    configuration:
#      gitProvider: aidan_github
#      path: a-murphy/5testRename5
#      buildOn:
#         commit: false
#         pullRequestCreate: false
#         pullRequestClose: false
#         releaseCreate: false
#         tagCreate: false
         
 # - name: fileSpec
 #   type: FileSpec
 #   configuration:
 #     sourceArtifactory: artifactory
 #     pattern: "$test-${versionTag}-*"
 #     recursive: true
 #     flat: ${testBoolean}
 #     limit: ${testNumber}
   #   offset: ${testNumber}
 # - name: dockerImage
 #   type: Image
 #   configuration:
 #     registry: docker
 #     imageName: "amurphy/test"
 #     imageTag: ${versionTag}
 #     autoPull: true
  - name: awsImage
    type: image
    configuration:
      registry: AWS
      imageName: "test"
      imageTag: ${versionTag}
      region: ${versionTag}
      autoPull: true
  - name: artifactoryImage
    type: IMAGE
    configuration:
      registry: artifactory
      sourceRepository: test
      imageName: "test"
      imageTag: ${versionTag}
      autoPull: ${testBoolean}
  - name: gcloudImage
    type: Image
    configuration:
      registry: gcloud
      imageName: "test"
      imageTag: ${versionTag}
      autoPull: true
  - name: outgoingWebhook2
    type: outgoingWebhook
    configuration:
      webhookName: outgoingWebhook
      method: "POST"
      parameters: ${versionTag}
      path: /test
      headers:
        Content-Type: ${versionTag}
  - name: inputBuildInfo
    type: Buildinfo
    configuration:
      sourceArtifactory: artifactory
      buildNumber: ${testNumber}
      buildName: ${versionTag}
 # - name: outputBuildInfo
 #   type: BuildInfo
 #   configuration:
 #     sourceArtifactory: artifactory
 #     buildNumber: ${testNumber}
 #     buildName: ${versionTag}
  - name: inputReleaseBundle
    type: releaseBundle
    configuration:
      sourceDistribution: distribution
      name: bundleName
      version: ${versionTag}
      isSigned: ${testBoolean}
  - name: outputReleaseBundle
    type: Releasebundle
    configuration:
      sourceDistribution: distribution
      name: bundleName
      version: ${versionTag}
      isSigned: ${testBoolean}
  - name: inputDistributionRule
    type: distributionRule
    configuration:
      sourceDistribution: distribution
      serviceName: service${versionTag}
      cityName: service${versionTag}
      siteName: site${versionTag}
      countryCodes:
        - ${versionTag}
        - ${testBoolean}
  - name: helmChart
    type: helmChart
    configuration:
      sourceArtifactory: artifactory
      repository: repo${versionTag}
      version: version${versionTag}
      chart: chart${versionTag}
  - name: outputHelmChart
    type: Helmchart
    configuration:
      sourceArtifactory: artifactory
      repository: repo${versionTag}
      version: version${versionTag}
      chart: chart${versionTag}
         
  - name: gitRepoResource3
    type: NotGitRepo
    configuration:
      gitProvider: github
      path: a-murphy/5testRename5
      buildOn:
         commit: false
         pullRequestCreate: false
         pullRequestClose: false
         releaseCreate: false
         tagCreate: false
 #        
 # - name: myImage
 #   type: Image
 #   configuration:
 #     registry: docker
 #     imageName: amurphy/test
 #     imageTag: master
      
 # - name: nodeRepoResource
 #   type: GitRepo
 #   configuration:
 #     gitProvider: aidan_github
 #     path: a-murphy/basic-node
 #     buildOn:
 #        commit: true
 #        pullRequestCreate: true
 #        pullRequestClose: false
 #        releaseCreate: true
 #        tagCreate: true
       
pipelines:
  - name: test_pipeline_20
    configuration:
   #   nodePool: Ubuntu16
      runtime:            
        type: host
    steps:
      - name: in_trigger_step
        type: bash
        configuration:
          affinityGroup: groupone
          runtime:            
            type: host
          inputResources:
            - name: gitRepoResource2
            - name: file
            - name: awsFile
            - name: gcloudFile
            - name: artifactoryFile
        #    - name: otherSourceGitRepo
       #   outputResources:
       #     - name: gitRepoResource3
       #     - name: myImage
         # integrations:
         #   - name: aidan_github
         #   - name: test4
        execution:
          onExecute:
            - update_commit_status gitRepoResource2
            - bump_semver v1.2.3 minor
            - echo "executing task command 1"
            - echo "executing task command 2"
            - openssl genrsa -out key.pem 1024 
            - openssl rsa -in key.pem -text -noout 
            - openssl rsa -in key.pem -pubout -out pub.pem 
            - openssl rsa -in pub.pem -pubin -text -noout 
            - echo "testing encryption" > testfile.txt
            - encrypt_file --output testencrypted.txt testfile.txt --key pub.pem
            - cat testencrypted.txt
            - decrypt_file testencrypted.txt --output testunencrypted.txt --key key.pem
            - cat testunencrypted.txt
            - encrypt_string "encryptme" --key pub.pem
            - encryptedstring=$(encrypt_string "encryptme" --key pub.pem)
            - echo "$encryptedstring"
            - decrypt_string "$encryptedstring" --key key.pem
         #   - write_output myImage "imageTag=$run_number" "sha=test"
            - sleep 10

      - name: main_step
        type: Bash
        configuration:
          environmentVariables:
            versionTag: testTag
            testNumber: 5
            testBoolean: "false"
          affinityGroup: groupone
     #     nodePool: Ubuntu16
          inputSteps:
            - name: in_trigger_step
          inputResources:
            - name: nodeRepoResource
            - name: fileSpec
            - name: dockerImage
            - name: awsImage
            - name: artifactoryImage
            - name: gcloudImage
            - name: cluster
          outputResources:
            - name: outgoingWebhook2
          integrations:
            - name: test
          runtime:
            type: image
            image:
              custom:
                name: drydock/u16node
                tag: master
        execution:
          onStart:
            - echo "Prepping build environment"
          onExecute:
            - echo "executing task command 1"
            - echo "executing task command 2"
            - set_payload outgoingWebhook2 "{"test":"$run_number"}"
            - compare_git --resource nodeRepoResource
            - cd "$res_nodeRepoResource_resourcePath"
          #  - switch_env nodejs 0.12
            - npm install
            - cd tests
            - ../node_modules/.bin/mocha --recursive "**/*.spec.js" -R mocha-junit-reporter --reporter-options mochaFile=../testresults.xml
            - ../node_modules/.bin/istanbul --include-all-sources cover -root "../routes" ../node_modules/mocha/bin/_mocha -- -R spec-xunit-file --recursive "**/*.spec.js"
            - ../node_modules/.bin/istanbul report cobertura --dir ../coverageReport
            - cd .. && ls
            - save_tests testresults.xml
            
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete: #always
            - echo "Cleaning up some stuff"
          onCancel:
            - echo "Someone cancelled the job"
      - name: create_step
        type: createReleaseBundle
        configuration:
          releaseBundleName: bundleName
          releaseBundleVersion: bundleVersion${versionTag}
          dryRun: ${testBoolean}
          sign: ${testBoolean}
          releaseNotes:
            content: ${testNumber}
            syntax: markdown
          environmentVariables:
            versionTag: testTag
            testNumber: 5
            testBoolean: "false"
          inputSteps:
            - name: main_step
          inputResources:
         #   - name: inputBuildInfo
         #   - name: outputBuildInfo
            - name: aql
          outputResources:
            - name: outputReleaseBundle
      - name: distribute_step
        type: distributeReleaseBundle
        configuration:
          environmentVariables:
            versionTag: testTag
            testNumber: 5
            testBoolean: "false"
       #   dryRun: true
          inputSteps:
            - name: main_step
          inputResources:
            - name: inputReleaseBundle
            - name: inputDistributionRule
          outputResources:
            - name: outputReleaseBundle
      - name: docker_build
        type: dockerBuild
        configuration:
          dockerFileLocation: .
          dockerFileName: test${versionTag}
          dockerImageName: image${versionTag}
          dockerImageTag: tag${versionTag}
          dockerOptions: "test${versionTag} --test ${testNumber}"
          environmentVariables:
            versionTag: testTag
            testNumber: 5
            testBoolean: "false"
          inputSteps:
            - name: main_step
          inputResources:
            - name: fileSpec
            - name: nodeRepoResource
      - name: docker_push
        type: dockerPush
        configuration:
          targetRepository: repo${versionTag}
          forceXrayScan: true
         # failOnScan: true
          autoPublishBuildInfo: true
          environmentVariables:
            versionTag: testTag
            testNumber: 5
            testBoolean: "false"
          inputSteps:
            - name: docker_build
          outputResources:
            - name: outputBuildInfo
          integrations:
            - name: artifactory

      - name: go_build_file
        type: goBuild
        configuration:
          sourceLocation: location${versionTag}
          repository: repo${versionTag}
       #   version: version${versionTag}
          goCommand: test command ${versionTag} $versionTag}
          outputLocation: output${testTag}
          outputFile: outputFile${testTag}
          noRegistry: ${testBoolean}
          publishDeps: ${testBoolean}
          environmentVariables:
            versionTag: testTag
            testNumber: 5
            testBoolean: "false"
          inputSteps:
            - name: main_step
          inputResources:
            - name: fileSpec
            - name: nodeRepoResource
      - name: go_publish_binary
        type: goPublishBinary
        configuration:
          targetRepository: repo
          autoPublishBuildInfo: true
          forceXrayScan: true
          failOnScan: false
          environmentVariables:
            versionTag: testTag
            testNumber: 5
            testBoolean: "false"
          inputSteps:
            - name: go_build_file
          integrations:
            - name: artifactory
          outputResources:
            - name: outputBuildInfo
      - name: go_publish_module
        type: goPublishModule
        configuration:
          targetRepository: repo
          version: version${versionTag}
          sourceLocation: .${versionTag}
          forceXrayScan: ${testBoolean}
          failOnScan: false
          autoPublishBuildInfo: ${testBoolean}
          self: ${testBoolean}
          deps: dep${versionTag}
          environmentVariables:
            versionTag: testTag
            testNumber: 5
            testBoolean: "false"
          inputSteps:
            - name: go_build_file
          inputResources:
            - name: nodeRepoResource
          integrations:
            - name: artifactory
          outputResources:
            - name: outputBuildInfo
      - name: go_build_artifactory
        type: goBuild
        configuration:
          sourceLocation: /
          repository: repo
          outputLocation: output
          outputFile: outputFile
          noRegistry: false
          publishDeps: false
          environmentVariables:
            versionTag: testTag
            testNumber: 5
            testBoolean: "false"
          inputSteps:
            - name: main_step
          integrations:
            - name: artifactory
          inputResources:
            - name: nodeRepoResource
      - name: gradle_build
        type: gradleBuild
        configuration:
          sourceLocation: /${testNumber}
          configFileLocation: fileLocation
          configFileName: shippable${testNumber}.yml
          gradleCommand: "gradle command ${testNumber}"
          forceXrayScan: true
          failOnScan: false
          environmentVariables:
            versionTag: testTag
            testNumber: 5
            testBoolean: "true"
          inputSteps:
            - name: main_step
          integrations:
            - name: artifactory
          inputResources:
            - name: nodeRepoResource
         #   - name: fileSpec
      - name: mvn_build
        type: mvnBuild
        configuration:
          sourceLocation: /${versionTag}
          configFileLocation: fileLocation${testNumber}
          configFileName: shippable.yml
          forceXrayScan: ${testBoolean}
          failOnScan: false
          mvnCommand: "maven command ${versionTag} $testNumber"
          environmentVariables:
            versionTag: testTag
            testNumber: 5
            testBoolean: "true"
          inputSteps:
            - name: main_step
          integrations:
            - name: artifactory
          inputResources:
            - name: nodeRepoResource
         #   - name: fileSpec
      - name: npm_build
        type: npmBuild
        configuration:
          sourceLocation: /${versionTag}
          repositoryName: test${versionTag}
          npmArgs: ${testNumber}test${versionTag}
          environmentVariables:
            versionTag: testTag
            testNumber: 5
            testBoolean: "false"
          inputSteps:
            - name: main_step
          integrations:
            - name: artifactory
          inputResources:
            - name: nodeRepoResource
            - name: fileSpec
      - name: npm_publish
        type: npmPublish
        configuration:
          repositoryName: repo${versionTag}
          forceXrayScan: ${testBoolean}
          autoPublishBuildInfo: false
          failOnScan: false
          environmentVariables:
            versionTag: testTag
            testNumber: 5
            testBoolean: "true"
          inputSteps:
            - name: npm_build
          integrations:
            - name: artifactory
      - name: helm_deploy
        type: helmDeploy
        configuration:
          releaseName: release
          dryRun: true
          environmentVariables:
            versionTag: testTag
            testNumber: 5
            testBoolean: "false"
          integrations:
            - name: artifactory
            - name: Kubernetes
          inputResources:
            - name: outputHelmChart
      - name: helm_deploy_repo
        type: helmDeploy
        configuration:
          releaseName: release
          dryRun: true
          chartPath: chart${versionTag}
          lint: ${testBoolean}
          test: true
          testFlags: ${versionTag}
          environmentVariables:
            versionTag: testTag
            testNumber: 5
            testBoolean: "false"
          integrations:
            - name: artifactory
            - name: Kubernetes
          inputResources:
            - name: nodeRepoResource
      - name: helm_publish
        type: helmPublish
        configuration:
          chartPath: path${versionTag}
          autoPublishBuildInfo: false
          flags: ${testNumber}
          environmentVariables:
            versionTag: testTag
            testNumber: 5
            testBoolean: "false"
          inputResources:
            - name: nodeRepoResource
          outputResources:
            - name: outputHelmChart
      - name: promote_step
        type: promoteBuild
        configuration:
          targetRepository: test
          includeDependencies: ${testBoolean}
          status: ${testNumber}
          comment: ${versionTag}
          copy: ${testBoolean}
          environmentVariables:
            versionTag: testTag
            testNumber: 5
            testBoolean: "true"
          inputSteps:
            - name: main_step
          inputResources:
            - name: inputBuildInfo
          outputResources:
            - name: outputBuildInfo
      - name: publish_step
        type: publishBuildInfo
        configuration:
          environmentVariables:
            versionTag: testTag
            testNumber: 5
            testBoolean: "true"
          envInclude: ${versionTag}
          envExclude: $versionTag
          forceXrayScan: ${testBoolean}
          failOnScan: false
          inputSteps:
            - name: main_step
          inputResources:
            - name: inputBuildInfo
          outputResources:
            - name: outputBuildInfo
      - name: push_artifactory
        type: pushArtifactoryPackage
        configuration:
          environmentVariables:
            versionTag: testTag
            testNumber: 5
            testBoolean: "true"
          targetRepo: ${versionTag}
          autoPublishBuildInfo: false
          forceXrayScan: ${testBoolean}
          failOnScan: false
          inputSteps:
            - name: npm_build
          inputResources:
            - name: inputBuildInfo
          integrations:
            - name: artifactory

      - name: sign_step
        type: signReleaseBundle
        configuration:
          environmentVariables:
            versionTag: testTag
            testNumber: 5
            testBoolean: "false"
          inputSteps:
            - name: main_step
          inputResources:
            - name: inputReleaseBundle
          outputResources:
            - name: outputReleaseBundle
      - name: xray_step
        type: xrayScan
        configuration:
          environmentVariables:
            versionTag: testTag
            testNumber: 5
   #         testBoolean: "false"
          failOnScan: false
          inputSteps:
            - name: main_step
          inputResources:
            - name: inputBuildInfo
          outputResources:
            - name: outputBuildInfo

