resources:
  - name: nodeRepoResource4
    type: GitRepo
    configuration:
      gitProvider: aidan_github
      path: a-murphy/sample_node
      branches:
        include: master
  - name: gitRepoResource
    type: GitRepo
    configuration:
      gitProvider: aidan_github
      path: a-murphy/5testRename5
      branches:
        include: {{gitBranch}}
  - name: dockerBuildBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory:    artifactory
      buildName:  initial
      buildNumber: 1
  - name: promotedBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory:    artifactory
      buildName:  initial
      buildNumber: 1
  - name: helmBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory:    artifactory
      buildName:  initial
      buildNumber: 1
  - name: releaseBundle
    type: ReleaseBundle
    configuration:
      sourceDistribution:    distribution
      name: myRelease
      version: ${run_number}
  - name: helmChart
    type: HelmChart
    configuration:
      sourceArtifactory: artifactory
      repository: example-repo-local/test/
      chart: my chart
      version: v1.1.1

pipelines:
  - name: webhook_pipeline
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: 192.168.50.42:8082/image/test #${versionTag}
          dockerImageTag: tag #${versionTag}
          #dockerOptions: "test${versionTag} --test ${testNumber}"
          environmentVariables:
            versionTag: testTag
            testNumber: 5
            testBoolean: "false"
          inputResources:
            - name: nodeRepoResource4
      - name: docker_promote
        type: PromoteBuild
        configuration:
          targetRepository: promoteRepository
          inputResources:
            - name: dockerBuildBuildInfo
          outputResources:
            - name: promotedBuildInfo
      - name: docker_push
        type: DockerPush
        configuration:
          targetRepository: test-docker
          forceXrayScan: ${testBoolean}
          autoPublishBuildInfo: true
          environmentVariables:
            versionTag: testTag
            testNumber: 5
            testBoolean: "false"
          inputSteps:
            - name: docker_build
          outputResources:
            - name: dockerBuildBuildInfo
          integrations:
            - name: artifactory
      - name: helmPublish
        type: HelmPublish
        configuration:
          chartPath: "my chart"
          flags: --debug
          autoPublishBuildInfo: true
          inputResources:
            - name: gitRepoResource
            - name: promotedBuildInfo
          outputResources:
            - name: helmChart
            - name: helmBuildInfo
      - name: createReleaseBundle
        type: CreateReleaseBundle
        configuration:
          dryRun: false
          releaseBundleName: myReleaseBundle
          releaseBundleVersion: ${run_number}
          inputResources:
            - name: helmBuildInfo
            - name: promotedBuildInfo
          outputResources:
            - name: releaseBundle
 
