resources:
  - name: buildInfo2
    type: BuildInfo
    configuration:
      sourceArtifactory: aidan_demoartifactory
      buildName:  name2
      buildNumber: 10
  - name: releaseBundle
    type: ReleaseBundle
    configuration:
      sourceDistribution: aidan_distribution
      name: releaseBundle
      version: "10"
      isSigned: false
  - name: releaseBundle2
    type: ReleaseBundle
    configuration:
      sourceDistribution: aidan_distribution
      name: releaseBundle
      version: "10"
      isSigned: false
  - name: releaseBundle3
    type: ReleaseBundle
    configuration:
      sourceDistribution: aidan_distribution
      name: releaseBundle
      version: "10"
      isSigned: false
  - name: distributionRule
    type: DistributionRule
    configuration:
      sourceDistribution: aidan_distribution
      serviceName: "*"
      siteName: "*"
      cityName: "*"
      countryCodes:
        - "*"
  - name: examples_repo
    type: GitRepo
    configuration:
      path: a-murphy/project-examples
      gitProvider: aidan_github
      branches:
        include: master

pipelines:
  - name: matrix
    configuration:
      nodePool: dynamicOne
    steps:
      - name: matrix_step
        type: Matrix
        stepMode: Bash
        configuration:
          multiNode: false
        stepletMultipliers:
          environmentVariables:
            - variable: one
            - variable: two
            - variable: three
        execution:
          onExecute:
            - echo "Executed matrix steplet - ${steplet_id} on node id - ${step_node_id}"
            - echo "value --> $variable"
            - sleep 10
  - name: test_pipeline_windows
    steps:  
      - name: BuildSampleWithAReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyLongName
        type: MvnBuild
        configuration:
          sourceLocation: artifactory-maven-plugin-example
          configFileLocation: .
          configFileName: config
          mvnCommand: "install -P release"
          inputResources:
            - name: examples_repo
          outputResources:
            - name: buildInfo2
          integrations:
            - name: aidan_demoartifactory
          autoPublishBuildInfo: true
          forceXrayScan: false
        execution:
          onStart:
            - '$env:testing = "testing1234"'
      - name: BuildSample
        type: MvnBuild
        configuration:
          sourceLocation: artifactory-maven-plugin-example
          configFileLocation: .
          configFileName: config
          mvnCommand: "install -P release"
          inputResources:
            - name: examples_repo
          outputResources:
            - name: buildInfo2
          integrations:
            - name: aidan_demoartifactory
          autoPublishBuildInfo: true
          forceXrayScan: false
        execution:
          onStart:
            - '$env:testing = "testing1234"'
      - name: createReleaseBundle
        type: CreateReleaseBundle
        configuration:
          releaseBundleName:        myReleaseBundle
          releaseBundleVersion:     "${run_number}"
          dryRun:                   false
          sign:                     false
          storeAtSourceArtifactory: "false"
          description:              "my description"
          releaseNotes:                         
            syntax:                markdown
            content:               "my release notes"
          inputResources:
            - name: buildInfo2
          inputSteps:
            - name: BuildSample
          outputResources:
            - name: releaseBundle
      - name: signReleaseBundle
        type: SignReleaseBundle
        configuration:
          inputResources:
            - name: releaseBundle
          outputResources:
            - name: releaseBundle2
      - name: distributeReleaseBundle
        type: DistributeReleaseBundle
        configuration:
          dryRun: false
          inputResources:
            - name: releaseBundle2
              trigger: false   
            - name: distributionRule
          outputResources:
            - name: releaseBundle3


 
 
