pipelines:
  - name: test_pipeline_bash
    configuration:
      nodePool: c7test
    steps:
      - name: in_trigger_step
        type: Bash
        configuration:    
          affinityGroup: groupone
          runtime:            
            type: host
        execution:
          onExecute:
            - echo "executing task command 1"
            - echo "executing task command 2"
            

      - name: main_step
        type: Bash
        configuration:
          inputSteps:
            - name: in_trigger_step
          runtime:
            type: image
            image:
              auto:
                language: Node
                versions:
                  - 10
        execution:
          onStart:
            - echo "Prepping build environment"
          onExecute:
            - 'echo "step_node_name: $step_node_name"'
            - 'echo "step_node_id: $step_node_id"'
            - 'echo "step_node_pool_name: $step_node_pool_name"'
            
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete: #always
            - echo "Cleaning up some stuff"
          onCancel:
            - echo "Someone cancelled the job"
