resources:
  - name: gitRepoResourceDocker
    type: GitRepo
    configuration:
      gitProvider: aidan_github
      path: a-murphy/5testRename5
      branches:
        include: dockerpipelines
  
  - name: outputDockerBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: aidan_artifactory
      buildName: test
      buildNumber: 1
  - name: outputDockerBuildInfo2
    type: BuildInfo
    configuration:
      sourceArtifactory: aidan_artifactory
      buildName: test
      buildNumber: 1
  - name: outputDockerBuildInfo3
    type: BuildInfo
    configuration:
      sourceArtifactory: aidan_artifactory
      buildName: test
      buildNumber: 1
  - name: outputDockerBuildInfo4
    type: BuildInfo
    configuration:
      sourceArtifactory: aidan_artifactory
      buildName: test
      buildNumber: 1
      
pipelines:
  - name: test_pipeline_1
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
 #         dockerFileLocation: .
 #         dockerFileName: Dockerfile
          dockerImageName: hts1.jfrog.io/docker-local/pipelinestestimage
          dockerImageTag: $run_number
          dockerOptions: "--build-arg RUN_NUMBER=${run_number}"
          inputResources:
            - name: gitRepoResourceDocker
              trigger: false
      - name: docker_push
        type: DockerPush
        configuration:
          targetRepository: docker-local
          autoPublishBuildInfo: true
          inputSteps:
            - name: docker_build
          outputResources:
            - name: outputDockerBuildInfo
          integrations:
            - name: aidan_artifactory
            
           
      
