pipelines:
  - name: Terraform
    steps:
    - name: terraform
      type: Bash
      configuration:
        integrations:
          - name: aidan_AWS
      execution:
        onExecute:
          - terraform init
          - terraform plan
