resources:
  - name: gitRepoResource_file_spec
    type: GitRepo 
    configuration:
      gitProvider: aidan_github
      path: a-murphy/5testRename5
      buildOn:
         pullRequestCreate: true
         pullRequestClose: false
         releaseCreate: true
         tagCreate: true
      branches:
        include: "{{gitBranch}}"
      tags:
        include: include.*
  - name: file_spec
    type: FileSpec
    configuration:     
      sourceArtifactory: aidan_artifactory
      target:  testfile.txt
      pattern: example-repo-local/my chart-v1.0.0.tgz
      buildName: HelmPublish
  - name: helmChart_file_spec
    type: HelmChart
    configuration:
      sourceArtifactory: aidan_artifactory
      repository: example-repo-local
      chart: my chart
      version: v1.1.1
  - name: buildInfo_file_spec
    type: BuildInfo
    configuration:
      sourceArtifactory: aidan_artifactory
      buildName: name
      buildNumber: number


pipelines:
  - name: test_pipeline_file_spec
    steps:
      - name: helmPublishFileSpec
        type: HelmPublish
        configuration:
          environmentVariables:
            JFROG_CLI_BUILD_NAME: HelmPublish
            JFROG_CLI_BUILD_NUMBER: $run_number
          chartPath: "./my chart"
          flags: --debug
          autoPublishBuildInfo: true
          inputResources:
            - name: gitRepoResource_file_spec
          outputResources:
            - name: helmChart_file_spec
            - name: buildInfo_file_spec
      - name: inFileSpec
        type: PowerShell
        configuration:
          inputSteps:
            - name: helmPublishFileSpec
          inputResources:
            - name: file_spec
        execution:
          onExecute:
            - echo "test"
 
 
