resources:
  - name: test_resource_one
    type: PropertyBag
    configuration:
      test: test
  - name: test_resource_two
    type: PropertyBag
    configuration:
      test: test
pipelines:
  - name: affinityGroup
    configuration:
      affinityGroup: myAffinityGroup
    steps:
    - name: stepOne
      type: Bash
      configuration:
        priority: 1
        chronological: true
      execution:
        onStart:
          - sleep 2
          - add_run_variables test1=$step_id
    - name: stepThree
      type: Bash
      configuration:
        inputSteps:
          - name: stepOne
        outputResources:
          - name: test_resource_two
      execution:
        onStart:
          - sleep 2
          - add_run_variables test3=$step_id
    - name: stepTwo
      type: Bash
      configuration:
        chronological: true
        inputSteps:
          - name: stepThree
        outputResources:
          - name: test_resource_one
      execution:
        onStart:
          - sleep 2
          - add_run_variables test2=$step_id
    - name: stepFour
      type: Bash
      configuration:
        inputResources:
          - name: test_resource_one
          - name: test_resource_two
            trigger: true
      execution:
        onStart:
          - sleep 2
    - name: matrix
      type: Matrix
      stepMode: Bash
      configuration: 
        multiNode: true
        inputSteps:
          - name: stepTwo
      stepletMultipliers:
        environmentVariables:
          - module: mod_1
          - module: mod_2
          - module: mod_3
          - module: mod_4                 
      execution:
        onExecute:
          - echo $module


