pipelines:
  - name: test_pipeline_2
    #setup:
    #  environmentVariables:
    #    readOnly:
    #      ENV1: value-pipe-1
    #      ENV2: value-pipe-2
    #  runtime:            
    #    type: host
    steps:
      - name: second_pipeline
        type: bash
        configuration:
          affinityGroup: test_group 
      #  requires:
      #    resources:
      #      - gitRepoResource2
        triggeredBy:
          resources:
            - gitRepoResource2
        #  steps:
        #    - in_trigger_step
        execution:
          onStart:
            - echo "Prepping build environment"
          onExecute:
            - echo "executing task command 1"
            - echo "executing task command 2"
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete:
            - echo "Cleaning up some stuff"
          onCancel:
            - echo "Someone cancelled the job"
