resources:
  - name: buildInfo2
    type: BuildInfo
    configuration:
      sourceArtifactory: aidan_artifactory
      buildName:  name2
      buildNumber: 10
  - name: examples_repo
    type: GitRepo
    configuration:
      path: a-murphy/project-examples
      gitProvider: aidan_github
      branches:
        include: master
  - name: this_repo
    type: GitRepo
    configuration:
      path: a-murphy/5testRename5
      gitProvider: aidan_github
      buildOn:
        pullRequestCreate: true
  - name: fileSpec
    type: FileSpec
    configuration:
      sourceArtifactory: aidan_artifactory
      pattern: test/*.txt

pipelines:
  - name: test_pipeline_windows4
    steps:  
      - name: BuildSampleWithAReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyLongName
        type: MvnBuild
        configuration:
          sourceLocation: artifactory-maven-plugin-example
          configFileLocation: .
          configFileName: config
          mvnCommand: "install -P release"
          inputResources:
            - name: examples_repo
          outputResources:
            - name: buildInfo2
          integrations:
            - name: aidan_artifactory
          autoPublishBuildInfo: true
          forceXrayScan: false
      - name: BuildSample
        type: MvnBuild
        configuration:
          sourceLocation: artifactory-maven-plugin-example
          configFileLocation: .
          configFileName: config
          mvnCommand: "install -P release"
          inputResources:
            - name: examples_repo
            - name: fileSpec
          outputResources:
            - name: buildInfo2
          integrations:
            - name: aidan_artifactory
          autoPublishBuildInfo: true
          forceXrayScan: true
  #    - name: MvnNoConfigFileName
  #      type: MvnBuild
  #      configuration:
  #        sourceLocation: artifactory-maven-plugin-example
      #    configFileLocation: .
  #        deployerSnapshotRepo: "test"
  #        mvnCommand: "install -P release"
  #        inputResources:
  #          - name: examples_repo
  #        outputResources:
  #          - name: buildInfo2
  #        integrations:
  #          - name: aidan_artifactory
  #        autoPublishBuildInfo: true
  #        forceXrayScan: false
  #    - name: MvnNoConfigFile
  #      type: MvnBuild
  #      configuration:
  #        sourceLocation: artifactory-maven-plugin-example
  #        inputResources:
  #          - name: examples_repo
  #        outputResources:
  #          - name: buildInfo2
  #        integrations:
  #          - name: aidan_artifactory
  #    - name: MvnDeployerSnapshot
  #      type: MvnBuild
  #      configuration:
  #        sourceLocation: artifactory-maven-plugin-example
  #        deployerSnapshotRepo: "test"
  #        inputResources:
  #          - name: examples_repo
  #        outputResources:
  #          - name: buildInfo2
  #        integrations:
  #          - name: aidan_artifactory
 
