resources:
  - name: maven_example_repo
    type: GitRepo
    configuration:
      path: ~aidanm/project-examples
      gitProvider: aidan_bbs
      branches:
        include: master

pipelines:
  - name: MavenPipeline
    steps:
    - name: MavenSample
      type: MvnBuild
      configuration:
        sourceLocation: artifactory-maven-plugin-example
        configFileLocation: .
        configFileName: config
        mvnCommand: "install -P release"
        inputResources:
          - name: maven_example_repo
        integrations:
          - name: artifactory
      execution:
        onStart:
          - update-ca-certificates -f
