resources:      
       
pipelines:
  - name: two_slashes
    steps:
      - name: main_step
        type: Bash
        configuration:
          environmentVariables:
            test: {{gitBranch.replace(\/\g, '%2F')}}
        execution:
          onExecute:
            - echo $test
