pipelines:
  - name: build_images_temp
    configuration:
      environmentVariables:
        readOnly:
          rtRegistry: "pipelines-docker"
          versionTag: "master"
          dockerRepo: "pipelines-docker.jfrog.io/jfrog"

    steps:
      - name: build_u18_node
        type: DockerBuild
        configuration:
          affinityGroup: "u18node"
          dockerFileLocation: "./u16/node"
          dockerFileName: "Dockerfile"
          dockerImageName: "$dockerRepo/pipelines-u18node-base"
          dockerImageTag: "$versionTag"
          integrations:
            - name: artifactory
          inputResources:
            - name: otherSourceGitRepo

      - name: push_u18_node
        type: DockerPush
        configuration:
          affinityGroup: "u18node"
          targetRepository: pipelines-docker
          integrations:
            - name: artifactory
          inputSteps:
            - name: build_u18_node

      - name: build_u18_node2
        type: DockerBuild
        configuration:
          affinityGroup: "u18node20"
          dockerFileLocation: "./u16/node"
          dockerFileName: "Dockerfile"
          dockerImageName: "$dockerRepo/pipelines-u18node-base"
          dockerImageTag: "$versionTag"
          integrations:
            - name: artifactory
          inputResources:
            - name: otherSourceGitRepo

      - name: push_u18_node2
        type: DockerPush
        configuration:
          affinityGroup: "u18node20"
          targetRepository: pipelines-docker
          integrations:
            - name: artifactory
          inputSteps:
            - name: build_u18_node2
            
            
      - name: build_u18_node4
        type: DockerBuild
        configuration:
          affinityGroup: "u18node4"
          dockerFileLocation: "./u16/node"
          dockerFileName: "Dockerfile"
          dockerImageName: "$dockerRepo/pipelines-u18node-base"
          dockerImageTag: "$versionTag"
          integrations:
            - name: artifactory
          inputResources:
            - name: otherSourceGitRepo

      - name: push_u18_node4
        type: DockerPush
        configuration:
          affinityGroup: "u18node4"
          targetRepository: pipelines-docker
          integrations:
            - name: artifactory
          inputSteps:
            - name: build_u18_node4
