resources:
  - name: cron
    type: CronTrigger
    configuration:
      interval: "0 */2 * * *"
pipelines:
  - name: cron_pipeline
    steps:
      - name: cronTriggered
        type: Bash
        configuration:
          inputResources:
            - name: cron
        execution:
          onExecute:
            - sleep 2
