resources:
  - name: terraformGitRepo
    type: GitRepo
    configuration:
      gitProvider: aidan_github
      path: a-murphy/5testRename5
      branches:
        include: Terraform

pipelines:
  - name: Terraform
    steps:
    - name: terraform
      type: Bash
      configuration:
        inputResources:
          - name: terraformGitRepo
        integrations:
          - name: aidan_AWS
        runtime:
          type: image
          image:
            custom:
              name: <string>                    # imageRepo/imageName format
              tag: <string>                     # version tag of the initial version of the Docker image
              options: "-e HOME=/root"        # Docker options
      execution:
        onExecute:
          - wget -nv https://releases.hashicorp.com/terraform/1.0.4/terraform_1.0.4_linux_amd64.zip
          - unzip -o terraform_1.0.4_linux_amd64.zip -d /tmp/terraform
          - sudo chmod +x /tmp/terraform/terraform
          - mv /tmp/terraform/terraform /usr/bin/terraform
          - cd $res_terraformGitRepo_resourcePath
          - chmod +x main.tf
          - terraform init
          - terraform plan
