resources:
  - name: cron2
    type: CronTrigger
    configuration:
      interval: "*/2 * * * *"
pipelines:
  - name: cron_pipeline
    steps:
      - name: cronTriggered
        type: Bash
        configuration:
          inputResources:
            - name: cron2
        execution:
          onExecute:
            - sleep 2
