resources:
  - name: gitRepoResource
    type: GitRepo
    configuration:
      gitProvider: aidan_github
      path: a-murphy/5testRename5
      buildOn:
         pullRequestClose: false
         releaseCreate: true
         tagCreate: true
  - name: gitRepoResource2
    type: GitRepo
    configuration:
      gitProvider: aidan_github
      path: a-murphy/5testRename5
      buildOn:
         commit: false
         pullRequestCreate: false
         pullRequestClose: false
         releaseCreate: false
         tagCreate: false
  - name: dockerImage
    type: Image
    configuration:
      registry: docker
      imageName: "amurphy/test"
      imageTag: ${versionTag}
      autoPull: true
  - name: nodeRepoResource
    type: GitRepo
    configuration:
      gitProvider: aidan_github
      path: a-murphy/basic-node
      buildOn:
         commit: true
         pullRequestCreate: true
         pullRequestClose: false
         releaseCreate: true
         tagCreate: true
       
pipelines:
  - name: test_pipeline_10
    configuration:
   #   nodePool: Ubuntu16
      runtime:            
        type: host
    steps:
      - name: in_trigger_step
        type: Bash
        configuration:
          affinityGroup: groupone
          runtime:            
            type: host
          inputResources:
            - name: gitRepoResource2
        execution:
          onExecute:
            - bump_semver v1.2.3 minor
            - echo "executing task command 1"
            - echo "executing task command 2"
            - openssl genrsa -out key.pem 1024 
            - openssl rsa -in key.pem -text -noout 
            - openssl rsa -in key.pem -pubout -out pub.pem 
            - openssl rsa -in pub.pem -pubin -text -noout 
            - echo "testing encryption" > testfile.txt
            - encrypt_file --output testencrypted.txt testfile.txt --key pub.pem
            - cat testencrypted.txt
            - decrypt_file testencrypted.txt --output testunencrypted.txt --key key.pem
            - cat testunencrypted.txt
            - encrypt_string "encryptme" --key pub.pem
            - encryptedstring=$(encrypt_string "encryptme" --key pub.pem)
            - echo "$encryptedstring"
            - decrypt_string "$encryptedstring" --key key.pem
         #   - write_output myImage "imageTag=$run_number" "sha=test"
            - sleep 10

      - name: main_step
        type: Bash
        configuration:
          environmentVariables:
            versionTag: testTag
            testNumber: 5
            testBoolean: "false"
          affinityGroup: groupone
     #     nodePool: Ubuntu16
          inputSteps:
            - name: in_trigger_step
          inputResources:
            - name: nodeRepoResource
          runtime:
            type: image
            image:
              custom:
                name: drydock/u16node
                tag: master
        execution:
          onStart:
            - echo "Prepping build environment"
          onExecute:
            - echo "executing task command 1"
            - echo "executing task command 2"
            - compare_git --resource nodeRepoResource
            - cd "$res_nodeRepoResource_resourcePath"
          #  - switch_env nodejs 0.12
            - npm install
            - cd tests
            - ../node_modules/.bin/mocha --recursive "**/*.spec.js" -R mocha-junit-reporter --reporter-options mochaFile=../testresults.xml
            - ../node_modules/.bin/istanbul --include-all-sources cover -root "../routes" ../node_modules/mocha/bin/_mocha -- -R spec-xunit-file --recursive "**/*.spec.js"
            - ../node_modules/.bin/istanbul report cobertura --dir ../coverageReport
            - cd .. && ls
            - save_tests testresults.xml
            
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete: #always
            - echo "Cleaning up some stuff"
          onCancel:
            - echo "Someone cancelled the job"
      - name: step_3
        type: Bash
        configuration:
          affinityGroup: grouptwo
          runtime:            
            type: host
          inputSteps:
            - name: main_step
        execution:
          onExecute:
            - sleep 10
      - name: step_4
        type: Bash
        configuration:
          affinityGroup: grouptwo
          runtime:            
            type: host
          inputSteps:
            - name: main_step
        execution:
          onExecute:
            - sleep 10
      - name: step_5
        type: Bash
        configuration:
          affinityGroup: grouptwo
          priority: 10
          runtime:            
            type: host
          inputSteps:
            - name: main_step
          outputResources:
            - name: dockerImage
        execution:
          onExecute:
            - sleep 10
      - name: step_6
        type: Bash
        configuration:
          affinityGroup: grouptwo
          priority: 5
          runtime:            
            type: host
          inputResources:
            - name: dockerImage
        execution:
          onExecute:
            - sleep 10
      - name: step_7
        type: Bash
        configuration:
          affinityGroup: groupthree
          runtime:            
            type: host
          inputSteps:
            - name: main_step
        execution:
          onExecute:
            - sleep 10
      - name: step_8
        type: Bash
        configuration:
          affinityGroup: groupthree
          runtime:            
            type: host
          inputSteps:
            - name: main_step
        execution:
          onExecute:
            - sleep 10
      - name: step_9
        type: Bash
        configuration:
          affinityGroup: groupfour
          priority: 10
          runtime:            
            type: host
          inputSteps:
            - name: main_step
        execution:
          onExecute:
            - sleep 10
      - name: step_10
        type: Bash
        configuration:
          priority: 5
          runtime:            
            type: host
          inputSteps:
            - name: step_5
        execution:
          onExecute:
            - sleep 10
